baseURL: "https://ramneko.xyz/"
languageCode: en-us
theme: PaperMod
enableEmoji: true

params:
  showAllSections : true
  ShowBreadCrumbs: true
  homeInfoParams:
    Title: 猫◾️汤屋
    Content: Though much is taken, much abides.

  socialIcons: # optional
    - name: "<微博>"
      url: "<https://weibo.com/u/3337374412>"
  mainSections:
    - 3Dimension
    - harukei
    - kamen
    - oc
  
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

taxonomies:
          category: categories
          tag: tags
          series: series
menu:
  main:
    - name: 目录
      url: archives
      weight: 5
    - name: 成分查询
      url: /search/
      weight: 10
    - name: 配料表
      url: tags
      weight: 5
    - name: OC
      url: /oc/
    - name: 三次元
      url: /3Dimension/
